# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 检查master分支
        uses: actions/checkout@master

      - name: 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20.18.0

      - name: 安装依赖
        run: npm install

      - name: build
        run: npm run docs:build
